version: '3'
services:
  framework:
    container_name: framework
    build:
      dockerfile: ./docker/Dockerfile
    image: centos:centos7
    ports:
      - '8080:8080'
    volumes:
      - '.:/var/www/html'
    command: bash -c 'cp /var/www/html/docker/.env /var/www/html/.env && /usr/sbin/httpd -D FOREGROUND'
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: 'mysql:5.7'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'framework'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    entrypoint: ['/entrypoint.sh', '--sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES', '--character-set-server=utf8', '--collation-server=utf8_general_ci']
    volumes:
      - './docker/mysql:/var/lib/mysql'
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  mysql:
    driver: local
